name: fauna
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons:
  country_calling_code_picker:
  otp_text_field:
  provider:
  carousel_slider:
  flutter_rating_bar:
  http:
  shared_preferences:
  cached_network_image:
  kf_drawer:
  dotted_border:
  image_picker:
  fluttertoast:
  image_cropper:
  multi_image_picker:
  screen_loader:
  share:
  flutter_google_places:
  flutter_image_compress:
  flutter_absolute_path:
  file_picker:
  flutter_pusher:
  intl:
  firebase_messaging:
  flutter_local_notifications:
  photo_view:
  firebase_core:
  geolocator:
  geocoder:
  google_sign_in:
  firebase_auth:
  flutter_facebook_login:
  uni_links:
  permission_handler:
  android_intent:

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/splash.webp
    - assets/logo.webp
    - assets/bg.webp
    - assets/login.webp
    - assets/fbLogo.webp
    - assets/mail.webp
    - assets/googleLogo.webp
    - assets/downArrow.webp
    - assets/forgot.webp
    - assets/verify.webp
    - assets/homeBg.webp
    - assets/breeder.webp
    - assets/chats.webp
    - assets/explore.webp
    - assets/favorites.webp
    - assets/profile.webp
    - assets/menu.webp
    - assets/filter.webp
    - assets/demo.webp
    - assets/sidebar/share.webp
    - assets/back.webp
    - assets/demo1.webp
    - assets/demo2.webp
    - assets/heart.webp
    - assets/cancel.webp
    - assets/edit.webp
    - assets/Breederbanner.webp
    - assets/location.png
    - assets/scan.webp
    - assets/my_post.webp
    - assets/unselectedHeart.webp
    - assets/phoneIcon.webp
    - assets/breedertag.png
    - assets/dots.webp
    - assets/edit.png
    - assets/verified.png
    - assets/cancelgradient.webp

    - assets/sidebar/Disputes.webp
    - assets/sidebar/fav.webp
    - assets/sidebar/invite.webp
    - assets/sidebar/paymnt.webp
    - assets/sidebar/promo.webp
    - assets/sidebar/settings.webp
    - assets/sidebar/subscription.webp
    - assets/sidebar/support.webp

    - assets/settings/accountSetting.webp
    - assets/settings/address.webp
    - assets/settings/changePassword.webp
    - assets/settings/lcoation.webp
    - assets/settings/notifaction.webp
    - assets/settings/phone.webp
    - assets/sidebar/mylist.png

    - assets/banner/Dispute.webp
    - assets/banner/share.webp
    - assets/banner/registerSuccesful.webp
    - assets/banner/emptyPost.webp
    - assets/banner/invite.webp
    - assets/banner/rating.webp

    - assets/beederSelectionGroup/selected.webp
    - assets/beederSelectionGroup/unselected.webp
    - assets/beederSelectionGroup/linedata.webp
    - assets/banner/Favorite.webp
    - assets/clippedCard.webp
    - assets/card_icon.png
    - assets/PaymentCards/
    - assets/postImage.webp
    - assets/
    - assets/sidebar/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
        - asset: fonts/Montserrat-SemiBold.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
